apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bluegreen-demo-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: bluegreen-demo.ishii.ga
    http:
      paths:
      - path: /
        backend:
          serviceName: bluegreen-demo
          servicePort: http