apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: argo.ishii.ga
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http